### ISSUE TITLE
Change shortcut

### ISSUE THREAD

**Issue by mallowigi** [uetchy/Polyglot#11]
Hi, 

The extension is very helpful, however the key shortcut choices are pretty limited (I use sometimes and it prevents the default behavior)

Is there a way to change it to something of our choice? Thanks

**Comment by uetchy** [comment]
Thank you for your feedback.
I'm currently working on this issue!

<img width="535" alt="screen shot 2016-09-07 at 8 28 33 pm" src="https://cloud.githubusercontent.com/assets/431808/18310514/c4b3d02a-7539-11e6-97c0-18d85f949c80.png">

**Comment by uetchy** [comment]
See [v2.0.0](https://github.com/uetchy/Polyglot/releases/tag/v2.0.0) :tada:
