### ISSUE TITLE
Bug: no setting available in the extension preferences 

### ISSUE THREAD

**Issue by Enrico68** [uetchy/Polyglot#121]
### Description

There is not setting for the native language, dont know how to set up. It just translate only  English (btw a language that I hate) 

### To Reproduce

just go preferences-->extension 

### Screenshots

![Schermata 2022-04-19 alle 13 26 59](https://user-images.githubusercontent.com/7678106/163993670-33babfda-c1f1-4bfe-a19a-1cf9c6981414.png)

### What's My Browser Link

whatsmybrowser.org/b/TVIJ9

### Polyglot Version

3.4

**Comment by gingerbeardman** [comment]
Please read the docs

https://github.com/uetchy/Polyglot#setup

> ## Setup
> 
> 1. Install `Polyglot.app` [from the Mac App Store](https://apps.apple.com/app/polyglot/id1471801525)
> 2. Open the `Polyglot.app` in `Applications`
> 3. Configure Settings in `Polyglot.app`
> 4. Open `Safari > Preferences > Extensions`
> 5. Activate `Polyglot` Extension
> 6. Extension is now available
> 
> Note: any pages that were already open before the extension was activated may need to be reloaded for the extension to work on them.
