### ISSUE TITLE
Feature request: 

### ISSUE THREAD

**Issue by kingescaped** [uetchy/Polyglot#131]
### Is your feature request related to a problem? Please describe.

I just downloaded it on the appstore and I selected the text and it can't be translated immediately, is there any way to make it translate as fast as yours?

### Describe the solution you'd like

I want to install when finished selecting text can be translated immediately

### Commitment

Join discussions

**Comment by gingerbeardman** [comment]
See #128 

Does that solve your issue @kingescaped ?
