### ISSUE TITLE
Bug: translation box disappears immediately 

### ISSUE THREAD

**Issue by nokuchi** [uetchy/Polyglot#134]
### Description

When I open a translation box, using any of the methods available: auto, menu bar, key combination, or icon confirm, the translation box appears for a second and then immediately closes, making it impossible to see what's on it.

### To Reproduce

1. Enable polyglot.
2. Highlight some text and use the appropriate method to view the translation.

### Expected behavior

One expects the translation box to stay open so that the contents can be read, but the box closes immediately.

### What's My Browser Link

https://www.whatsmybrowser.org/b/0WDRT

### Polyglot Version

3.4

**Comment by gingerbeardman** [comment]
See https://github.com/uetchy/Polyglot/issues/128#issuecomment-1487229870 for workaround
