### ISSUE TITLE
No translation, loading infinitely

### ISSUE THREAD

**Issue by mcxnet** [uetchy/Polyglot#14]
![screenshot_translate-ext](https://cloud.githubusercontent.com/assets/8062159/20493654/0a504436-b01a-11e6-95b5-188832980fa1.png)

If I try to translate something, in the popup view me the loading infinitely (see above screenshot).
Do you have a fix about it?
Thanks.

**Comment by uetchy** [comment]
Could you show me development console log? It'll be so helpful.

**Comment by mcxnet** [comment]
The development console log is empty.
Is it necessary set an API for Google Cloud Platform? Now, I haven't insert anything (FYI, the guide in the wiki section has the the images/screenshots broken).
Thanks.

**Comment by uetchy** [comment]
You don't need set an API key so it's merely buggy behaviour.
Tell me the websites url which cause infinity loading?
I'll dig into them.

**Comment by mcxnet** [comment]
Unfortunately not works with all websites.
I've tried to disable all other safari extensions (to avoid conflict), I've changed the language (from default japanese to italian/french etc.) but... nothing to do.
I'm using the last version of macOS (10.12.1) and Safari (10.0.1).

**Comment by uetchy** [comment]
It seems Polyglot in Safari Extension Gallery is outdated. (latest version is 2.0.1)
Have you tried latest version of Polyglot?

https://github.com/uetchy/Polyglot/releases/download/v2.0.1/Polyglot.safariextz

If installation failed, delete previous version and try it again.

**Comment by mcxnet** [comment]
Yes, the problem is with outdated version of Safari Extension Gallery.
I've installed the GitHub version and now works good.
A last question, for the Polyglot updates is necessary to download them every time from GitHub or Safari update automatically?

**Comment by uetchy** [comment]
Awesome!
I've already submitted latest version of Polyglot to Safari Extension Gallery and waiting for a response.
Anyway, You can download latest version from GitHub anytime 😄

**Comment by mcxnet** [comment]
Ok, thanks!
