### ISSUE TITLE
Bug: Not working after update

### ISSUE THREAD

**Issue by zexir** [uetchy/Polyglot#141]
### Description

Hi,
Not working after update. Will you release an update?
Thanks

### To Reproduce

**shortcut** and **toolbar button** doesn't work.

### What's My Browser Link

https://www.whatsmybrowser.org/b/GM6ST

### Polyglot Version

Version 3.4 (3.4.0)

**Comment by gingerbeardman** [comment]
@zexir what have you updated? macOS, Safari?

Does the workaround in https://github.com/uetchy/Polyglot/issues/128#issuecomment-1554539501 work for you?

There is no new version of Polyglot and there likely won't be because the owner is... gone.

**Comment by levenecav** [comment]
Polyglot stopped working after updating MacOS to Sonoma 14

**Comment by gingerbeardman** [comment]
@levenecav see the link in the comment above, and if it still doesn't work please start a new issue
