### ISSUE TITLE
No images on page "How to obtain Google Cloud Platform API key"

### ISSUE THREAD

**Issue by Denages** [uetchy/Polyglot#15]
Please, repair images on the page "How to obtain Google Cloud Platform API key"

**Comment by uetchy** [comment]
Thank you for reporting this issue 😄 
ICYMI: the latest version of Polyglot no longer requires API key.

https://github.com/uetchy/Polyglot/releases/tag/v2.0.1

**Comment by uetchy** [comment]
@Denages Is everything OK?

**Comment by Denages** [comment]
@uetchy  Yes. Thanks a lot. Now I'm using version 2.0.1.
