### ISSUE TITLE
Keyboard shortcuts doesn't work 

### ISSUE THREAD

**Issue by d1monster** [uetchy/Polyglot#17]
Hello! 
In the last Polyglot 2.0.1 keyboard shortcuts, which set up in Safari settings, as well as ` symbol, does not work (Safari 10.0.3, macOS 10.12.3).
Could you please check?

**Comment by bezvoshchuk** [comment]
Update: just noticed that letter 't' does not work within the display window when extension is turned on.

**Comment by uetchy** [comment]
Any error message in console log?

**Comment by bezvoshchuk** [comment]
Letter 'T' began to work after relaunching extension, but keyboard shortcuts still don't work.
No errors or warnings in the console.

**Comment by uetchy** [comment]
Could you set a keyboard shortcut combined with control or command or whatever meta key?
And tell me if the issue still occurs.

**Comment by bezvoshchuk** [comment]
Double combining works, in my case Shift+Ctrl+9.
Thanks.

**Comment by locovna** [comment]
I had same issue, same versions and same solution (bind to Shift+Ctrl+1)
Thanks!

But I notice some errors in console:
(they disappear after binding to another keys)

<img width="1111" alt="screen shot 2017-03-17 at 14 23 36" src="https://cloud.githubusercontent.com/assets/15370225/24043210/344a2298-0b1e-11e7-9a0b-c7111ecc510a.png">
<img width="820" alt="screen shot 2017-03-17 at 14 23 28" src="https://cloud.githubusercontent.com/assets/15370225/24043209/341ea7da-0b1e-11e7-801a-c26b251ff6be.png">

**Comment by lenk1111** [comment]
On the shortcut key does not take effect, I found a way, in the preferences - extension, the first unchecked, and then restart Safari

**Comment by osenvosem** [comment]
The same issue here.
![screen shot 2017-06-11 at 10 37 39](https://user-images.githubusercontent.com/6762673/27009260-1a7ac158-4e92-11e7-86ab-e6d3c84ac011.jpg)

**Comment by uetchy** [comment]
@osenvosem Would you let me see your extension settings of Polyglot?

**Comment by osenvosem** [comment]
@uetchy sure.
![screen shot 2017-06-15 at 08 39 40](https://user-images.githubusercontent.com/6762673/27166882-5187ef88-51a6-11e7-8cdb-d03356fff4c3.jpg)

**Comment by uetchy** [comment]
@osenvosem Did you try some key combination with any special key? (such as Ctrl).
Or you might want to use another key, not 't'.

**Comment by locovna** [comment]
Maybe you may set required key combination (Ctrl, Command, Shift) to default? To not confuse new users.
Is it possible, @uetchy?

**Comment by osenvosem** [comment]
@uetchy Only Cmd+Shift+char combinations work. It is better instead/with the combination to use a float button like in the Google Translate extension for Chrome. Also it would be nice if the output more informative, not just a single word, like, again, I is done in the Google's extension.

**Comment by japerezf** [comment]
Double combining works, in my case Ctrl+Alt+.
Thanks.

 >@osenvosem: Also it would be nice if the output was more informative, not just a single word, like, again, It is done in the Google's extension.

I agree with him

**Comment by harunyasar** [comment]
Any shortcut doesn't work properly. Say I set the 1 as a shortcut when you try to write comment on Facebook it won't work.

**Comment by uetchy** [comment]
Keyboard shortcuts without meta keys may cause event confliction.
@harunyasar Have you ever tried shortcuts with meta keys and have same issue so?
<img width="551" alt="screen shot 2017-12-04 at 17 27 02" src="https://user-images.githubusercontent.com/431808/33542926-61cc006a-d918-11e7-8a86-e7843ca60700.png">

**Comment by harunyasar** [comment]
Yeah it does work with some key combinations like cmd+shift+1.

**Comment by spn13** [comment]
Hello.

Version 2.2.0

When keyboard layout is not English (e.x. Russian), shortcut doesn't work. I need It didn't depend on keyboard layout, or add please settings for second shortcut.

**Comment by uetchy** [comment]
@spn13 Any sample of the Russian keys (and screenshot of the settings if you don't mind)? So we can test it and fix this issue.

**Comment by spn13** [comment]
On my keyboard it is "]"
<img width="651" alt="2017-12-22 14 44 44" src="https://user-images.githubusercontent.com/34765794/34297037-b52cc34a-e726-11e7-8af8-342973513506.png">

![img_1622](https://user-images.githubusercontent.com/34765794/34297105-286783f4-e727-11e7-8ce6-859beade5a9d.jpg)

**Comment by uetchy** [comment]
@spn13 Thanks. In Russian keyboard, can `]` be typed without any special key? If not, Put a check on `Shift` on settings could fix this issue.

**Comment by uetchy** [comment]
@spn13 Could you access [keycode checker](http://keycode.info/) and type the key you want to configure then tell me what they have shown.

**Comment by spn13** [comment]
@uetchy 

In English 192 (grave accent / ñ / æ / ö) In Russian 221 (close bracket / å). I want configure for both keys

**Comment by uetchy** [comment]
@spn13 Thanks. You can use either of the layout of keyboards but unfortunately cannot configure multiple key code point for now.
If you are interested in implementing multiple key code support, please consider to create a pull request!

**Comment by gingerbeardman** [comment]
Key shorcuts no working for me.

I set Cmd+Shift+t but simply pressing t invokes Polyglot.
And then letter t cannot be typed in Safari.

Some double modifier combinations work, but it remains that pressing the key without any modifiers triggers Polyglot.

**Comment by gingerbeardman** [comment]
Saw this and thought of plolyglot 😨 
http://antrikshy.com/blog/safari-extension-development-keyboard-shortcuts

**Comment by uetchy** [comment]
@gingerbeardman That's just what Polyglot doing!

**Comment by gingerbeardman** [comment]
@uetchy if so, then why...

> I set Cmd+Shift+t but simply pressing t invokes Polyglot.
> And then letter t cannot be typed in Safari.

**Comment by uetchy** [comment]
@gingerbeardman Doesn't work in the latest version? If so, would you consider writing a PR for this⚡️ (Currently, I have no much time to delve into this issue)

**Comment by gingerbeardman** [comment]
I will look into it :)

**Comment by gingerbeardman** [comment]
Oh! I installed through Apple Safari Extension gallery and no update has been reported. So I am on 2.2.0 

I see 2.3.0 is available on your GitHub release page, but it will not install in my Safari. Certificate problem?

**Comment by gingerbeardman** [comment]
Actually, default shortcut Ctrl+` does not work for me.
And Alt+` also does not work for me. Why?

However Cmd+Shift+` works for me so I will stick with that.

**Comment by z234009184** [comment]
I had same issue

**Comment by uetchy** [comment]
Close this issue as there are many changes added since this issue was created. Create new issue if the problem continues.
