### ISSUE TITLE
Error in injected.entry.js on line 8231

### ISSUE THREAD

**Issue by eisenhorn13** [uetchy/Polyglot#21]
There is error in injected.entry.js on line 8231:
`var applyKey = settings.keyValue.charCodeAt(0) === e.keyCode;`

It fires any time key pressed.

Polyglot version is 2.0.1 and Safari 11.0 (13604.1.38.1.6).

<img width="1433" alt="2017-09-28 13 04 23" src="https://user-images.githubusercontent.com/17888717/30961027-957ac40a-a44d-11e7-8b69-599df6aef21a.png">

**Comment by uetchy** [comment]
I have same version of Polyglot and Safari however I couldn't reproduce the error.
What's your keyboard shortcuts settings?

This is my settings FYI:
<img width="535" alt="screen shot 2017-09-29 at 10 55 37" src="https://user-images.githubusercontent.com/431808/30997721-c17da9a2-a504-11e7-8e89-e2ac920e55d7.png">

**Comment by eisenhorn13** [comment]
I have same key, but no keyboard modifier and that`s the key.

**Comment by uetchy** [comment]
It seems weird because I have no issue without keyboard modifiers.
Try to clear __Key__ field and close the settings window, then put a new key to __Key__ again and reload web pages.

**Comment by 99sono** [comment]
Hi, this issue appears to be related to:
https://stackoverflow.com/questions/46268576/angular-4-safari-settings-object-without-keyvalue-property-defined

**Comment by uetchy** [comment]
Updated to v2.1.0
- Suppress errors for invalid keyboard shortcuts

https://github.com/uetchy/Polyglot/releases/tag/v2.1.0

**Comment by uetchy** [comment]
See [v2.2.0](https://github.com/uetchy/Polyglot/releases/tag/v2.2.0) for fixing this issue.
