### ISSUE TITLE
Two different Polyglot in Safari Extensions gallery?

### ISSUE THREAD

**Issue by gingerbeardman** [uetchy/Polyglot#23]
https://safari-extensions.apple.com/?q=polyglot

2.0.1
2.2.0

**Comment by uetchy** [comment]
Thank you for letting me know the duplication problem in the gallery.
I've reported this issue to Apple Support.

**Comment by uetchy** [comment]
Apple confirmed that this is due to Bundle ID mismatch.
And now the issue has closed.
