### ISSUE TITLE
Mojave discontinues support for old style extensions

### ISSUE THREAD

**Issue by gingerbeardman** [uetchy/Polyglot#26]
https://9to5mac.com/2018/06/09/safari-12-extensions-more/

If you do not wish to release the plugin through the App Store, I would be happy to release it for you on my account?

**Comment by uetchy** [comment]
I'm going to publish the extension on Mac App Store as well.
However, I've already enrolled in the Developer Program so I can publish it myself.
Anyway, I appreciate your gentle request!
