### ISSUE TITLE
[BUG] Instant translation unexpectedly appearing when selecting text in text fields

### ISSUE THREAD

**Issue by gingerbeardman** [uetchy/Polyglot#28]
I'm seeing auto-translate appearing when text field are focused on GitHub @isswp101

For example as I am typing this if I double-click a word auto-translate will unexpectedly appear.

![2018-08-05 22_26_46](https://user-images.githubusercontent.com/49612/43690265-45fa888c-98ff-11e8-9263-2952e419aeec.gif)

**Comment by uetchy** [comment]
This could be suppressed by putting HTML elements constraint on the click handler.
What do you think? @isswp101

**Comment by isswp101** [comment]
@uetchy do you mean the text received from `input`, `textarea` and so on should not be translated by click?
