### ISSUE TITLE
Extension expired / can't install new

### ISSUE THREAD

**Issue by JayBrown** [uetchy/Polyglot#35]
Safari just disabled an older version of the Polyglot extension & moved it to the trash. Trying to install the new one released 10 days ago fails

**Comment by gingerbeardman** [comment]
Yes, something has gone wrong. I saw the same thing.

<img width="532" alt="screen shot 2018-08-15 at 10 51 16" src="https://user-images.githubusercontent.com/49612/44142799-4b79a4d8-a079-11e8-991f-43f28c9644f0.png">

2.2.0 is still in the Apple Extensions Gallery
https://safari-extensions.apple.com/details/?id=io.uechi.safari.polyglot-58XDWHK3JX

**Comment by uetchy** [comment]
My previous certificate has been revoked :( I'll put newly generated certificate into next release so it will be ok.

**Comment by uetchy** [comment]
[v2.4.1](
https://github.com/uetchy/Polyglot/releases/tag/v2.4.1) hopefully fixes those issue. check it out.

**Comment by gingerbeardman** [comment]
Still a problem  with 2.5.0

<img width="532" alt="screen shot 2018-08-16 at 13 44 23" src="https://user-images.githubusercontent.com/49612/44209163-8bd63500-a15a-11e8-804b-540d62d37c96.png">

**Comment by protectedMan** [comment]
![image](https://user-images.githubusercontent.com/17565737/44209179-44b96580-a195-11e8-9167-2a532e456b40.png)

**Comment by uetchy** [comment]
You must uninstall the old plugin before installing a new one.

@protectedMan What that message indicates to?

**Comment by JayBrown** [comment]
2.5.0 is working again! Thank you.
