### ISSUE TITLE
Pop-up translate always if double-click any word in webpage

### ISSUE THREAD

**Issue by alseg** [uetchy/Polyglot#38]
OSX 10.12.6
Safari 11.1.2 (12605.3.8.1)
Polyglot 2.4.0

Issue:
Pop-up translate always if double-click any word in webpage

**Comment by gingerbeardman** [comment]
There's an option in extension preferences to disable this feature

**Comment by alseg** [comment]
@gingerbeardman thankyou! this is my fault
