### ISSUE TITLE
Translation doesn't pop-up

### ISSUE THREAD

**Issue by mdyyyy** [uetchy/Polyglot#40]
Whenever I select a text and click on translate, it just never appeared. 
macOS High Sierra
Version 10.13.6
Safari

**Comment by MarkPi** [comment]
FYI, I had a somewhat opposite issue - selected text was instantly translated without ever enabling instant translation in Preferences > Extensions.
 - Checking, then Unchecking the box resolved it. 
macOS High Sierra
Version 10.13.6
Safari 12.0

**Comment by nitramwin** [comment]
I want to report that since installing, instant translations occurred constantly even with Instant Translations>OFF. Checking and unchecking the box has fixed the issue.

**Comment by gingerbeardman** [comment]
@MarkPi & @nitramwin this is a known issue  https://github.com/uetchy/Polyglot/issues/46
