### ISSUE TITLE
`undefined` result

### ISSUE THREAD

**Issue by at-vinhdo** [uetchy/Polyglot#41]
Sometimes, I try to translate a word, but the result always was `undefined`.
Restarting OS & Browser was ineffective.
I using Safari 11.0.3.

**Comment by gingerbeardman** [comment]
what version of Polyglot?

**Comment by at-vinhdo** [comment]
I using v2.4.0

**Comment by gingerbeardman** [comment]
what are the source and destination languages?

do you have a good network and internet connection?

**Comment by at-vinhdo** [comment]
I'm want to translate from English to Vietnamese.
my network and internet connection also stables
This error began to appear from about 3 weeks ago

**Comment by gingerbeardman** [comment]
Thanks for the info!

I can now reproduce the problem and will look into it.

**Comment by gingerbeardman** [comment]
OK, the problem seems to be that for each user the number of requests are limited by the external translation service. 

So you can only request a certain amount of translations, then you have to wait for a while.

@uetchy maybe the list can be tracked and shown in UI?

**Comment by at-vinhdo** [comment]
@gingerbeardman Oh! I got it,
Thank you for your clear explanation.

**Comment by uetchy** [comment]
@gingerbeardman Indeed. It should be shown on the message panel. filed #42 for this issue.

**Comment by gingerbeardman** [comment]
See #55
