### ISSUE TITLE
Words limit

### ISSUE THREAD

**Issue by sherlockblaze** [uetchy/Polyglot#44]
Hi there,
The limitations of the interface call made me feel very hard, so I modified the api that was called, but I can't package it. Can you help me?
Tks

**Comment by gingerbeardman** [comment]
https://code.tutsplus.com/tutorials/how-to-create-a-safari-extension-from-scratch--net-15050

**Comment by sherlockblaze** [comment]
@gingerbeardman that's nice, thank you.
