### ISSUE TITLE
Wrong default value for `Instant translation` feature in Settings Panel

### ISSUE THREAD

**Issue by agurodriguez** [uetchy/Polyglot#46]
On a fresh installed Polyglot instance I'm observing the following behavior:

On Settings panel it shows the `Instant translation` feature disabled, but in reality it is enabled (I select text on any webpage and I show the tooltip).

If I uncheck and then check again the setting the feature gets disabled.

---

<img width="775" alt="screen shot 2019-01-26 at 4 09 11 pm" src="https://user-images.githubusercontent.com/13837769/51792806-d685bf80-2184-11e9-8a23-65fdfcac170f.png">

**Comment by gingerbeardman** [comment]
I can confirm this

**Comment by uetchy** [comment]
Closes as the new version has fixes on this.
