### ISSUE TITLE
Polyglot generates errors in Kibana text fields

### ISSUE THREAD

**Issue by ooii** [uetchy/Polyglot#47]
Hi,

I'm using Polyglot since several months and never had any issue until I started using [Kibana](https://github.com/elastic/kibana).
When the extension is enabled, Kibana hangs as soon as I start writing text in text fields. I opened [an issue](https://github.com/elastic/kibana/issues/29809) at Kibana and I open one here.

**Comment by uetchy** [comment]
Close this issue due to inactivities. If the glitch still exists in the latest version, reopen it.
