### ISSUE TITLE
Setting the native language

### ISSUE THREAD

**Issue by jaredchu** [uetchy/Polyglot#48]
Is there any extension setting that I can change my native language?

**Comment by gingerbeardman** [comment]
Have you checked Safari > Preferences > Extensions > Target Language?

![GitHawk Upload by gingerbeardman](https://i.imgur.com/WTEu0BJ.jpg)

**Comment by jaredchu** [comment]
@gingerbeardman thank you, I didn't see the setting before I created this issue so I closed it.

**Comment by Enrico68** [comment]
There is not setting for the native language, dont know how to set up. It just translate only  English (btw a language that I hate) 

![Schermata 2022-04-19 alle 13 26 59](https://user-images.githubusercontent.com/7678106/163993670-33babfda-c1f1-4bfe-a19a-1cf9c6981414.png)
