### ISSUE TITLE
Could you consider supporting other browsers

### ISSUE THREAD

**Issue by abc408880155** [uetchy/Polyglot#51]
Could you consider supporting other browsers

**Comment by uetchy** [comment]
Taking Chrome, for example, supporting it would be nice but there are already several extensions available up there.
- [Google Translate](https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb)
- [Remenberry](https://chrome.google.com/webstore/detail/rememberry-translate-and/dipiagiiohfljcicegpgffpbnjmgjcnf)

**Comment by uetchy** [comment]
We are working on shifting to Swift + JavaScript codebase so it's going to be less shared codebase between Safari extension and others. That's another con to support browsers other than Safari.
