### ISSUE TITLE
Show meaningful error message when API limit is exceeded

### ISSUE THREAD

**Issue by uetchy** [uetchy/Polyglot#55]
Show meaningful error message when API limit is exceeded.
Originally PR #45 fixed this issue but Swift transformation process caused some regression.

**Comment by gingerbeardman** [comment]
stale bot is annoying

**Comment by uetchy** [comment]
should stop it later

**Comment by gingerbeardman** [comment]
@uetchy lots of recurring issues for this, I have collected them above.
