### ISSUE TITLE
Add context menu to translate whole page?

### ISSUE THREAD

**Issue by gingerbeardman** [uetchy/Polyglot#56]
**Describe the solution you'd like**
Sometimes, after translating using Selection I decide that I would rather translate the Whole Page.

**Describe alternatives you've considered**
I have previously used the Translate extension from SideTree.com

**Possible solutions**
1. (preferred) in-place translation 
  https://www.w3schools.com/howto/howto_google_translate.asp
2. redirection translation 
  `javascript:location='http://translate.google.com/translate?langpair=auto|en&u='+encodeURIComponent(location)`

**Comment by gingerbeardman** [comment]
For this I now use: Myna for Google Translate Trial version from https://madbirdies.com

Feel free to close.

**Comment by uetchy** [comment]
As "translate whole page" has been available since Safari 14, this Issue can be safely closed.

**Comment by gingerbeardman** [comment]
> As "translate whole page" has been available since Safari 14, this Issue can be safely closed.

Do you mean macOS/Safari feature? If so, this is not available for all languages. For example I cannot translate Japanese to English.
