### ISSUE TITLE
Key press debugging is still activated

### ISSUE THREAD

**Issue by gingerbeardman** [uetchy/Polyglot#57]
**Describe the bug**
There is still key press debug logging activated.

**To Reproduce**

1. Open web inspector
2. Press a key on page
3. Watch console log

**Expected behavior**
No key press debugging

**Screenshots**
![Screen shot 2019-07-19 at 14 53 46](https://user-images.githubusercontent.com/49612/61540183-0d060e00-aa35-11e9-86a1-d65a1befbe07.png)

**Comment by uetchy** [comment]
fixed e04e971fb5335257170dca40f8b8a4e25628a96c
