### ISSUE TITLE
Transliteration

### ISSUE THREAD

**Issue by uetchy** [uetchy/Polyglot#59]
Show transliteration of source text that allow us to figure out how it be pronounced.

**Comment by erkanyildiz** [comment]
Would you be interested in a PR that adds transliteration support based on `CFStringTokenizer`: https://developer.apple.com/documentation/corefoundation/cfstringtokenizer?language=objc

For Japanese it would look like this:

<img width="1530" alt="transliteration" src="https://user-images.githubusercontent.com/1222652/105624409-d187a380-5e64-11eb-8955-5eac085dc0eb.png">
<img width="752" alt="transliteration_2" src="https://user-images.githubusercontent.com/1222652/105624414-da787500-5e64-11eb-83e2-16e023508721.png">

It is not perfect but works most of the time.

I have not tried for other languages yet.

**Comment by gingerbeardman** [comment]
I'm not the maintainer of this project, but I think this is a useful feature. 

It would save me opening Google Translate.

**Comment by uetchy** [comment]
Now that I'm convinced of the usefulness of this feature, well... here's a screenshot from my dev build.
<img width="621" alt="Screen Shot 2021-01-25 at 1 04 38 PM" src="https://user-images.githubusercontent.com/431808/105660220-ebc98c00-5f0d-11eb-88ea-d3f346349367.png">

**Comment by gingerbeardman** [comment]
Transliteration works well.

I'd like to see it presented visually different to the normal translation so that it is visually distinct. Perhaps using smaller text?
