### ISSUE TITLE
Not working with Safari 13

### ISSUE THREAD

**Issue by michalzielanski** [uetchy/Polyglot#66]
I updated Safari to version 13, installed Polyglot from the Mac App Store (version 3.0.1) and it doesn't work.
There is no icon in the browser. The configured keyboard shortcut does not work.
How can I diagnose where the problem is?

**Comment by gingerbeardman** [comment]
Move the Polygot app to another folder and then back to Applications. The entry in Safari Extensions window should then appear.

**Comment by michalzielanski** [comment]
It works. The extension was not be selected in Preferences -> Extensions.
Thank you for your help.

**Comment by uetchy** [comment]
It should be documented in README

**Comment by ollyde** [comment]
Unfortunately it seems to be broken again, loading from the App store

**Comment by gingerbeardman** [comment]
@ollyde for workaround see https://github.com/uetchy/Polyglot/issues/128#issuecomment-1487004558
