### ISSUE TITLE
Polyglot doesn't show language select menu in safari preferance

### ISSUE THREAD

**Issue by dh1789** [uetchy/Polyglot#69]
polyglot does not show the bottom menu in safari preferences
- Language setting
- Shortcuts

The language is not set and translated into English
![image](https://user-images.githubusercontent.com/12591264/66009793-03019080-e4f7-11e9-8ee5-ffa599581284.png)

**Comment by uetchy** [comment]
It's an old version of the extension. Try the latest version instead.
https://apps.apple.com/jp/app/polyglot/id1471801525?l=en&mt=12

**Comment by dh1789** [comment]
thank you @uetchy 
I didn't know changed setting method
polyglot is very useful in safari extension apps!
