### ISSUE TITLE
Can't use

### ISSUE THREAD

**Issue by dai706540** [uetchy/Polyglot#77]
<img width="977" alt="image" src="https://user-images.githubusercontent.com/53268677/85972641-21070d80-ba03-11ea-928f-e72f3b02ef59.png">
As the picture shows, I can't use this app and I don't know why. When I use it the first time, everything goes well.
I'm in China, and I've used VPN.

**Comment by gingerbeardman** [comment]
The spinner appears whilst Google Translate returns the result.

**Comment by dai706540** [comment]
Thanks for your reply. Now it works, but sometimes the spinner appears without the result. It's a perfect plugin, I like it.

**Comment by gingerbeardman** [comment]
There is a limiter by Google Translate, if you use it too much within a certain time period there will be no results. Please wait a while and try again.

**Comment by dai706540** [comment]
Thanks a lot, so kind of you!
