### ISSUE TITLE
Polyglot does not work sometimes

### ISSUE THREAD

**Issue by minhdn122** [uetchy/Polyglot#82]
The utility is great but I don't know why it can be used sometimes?
I'm using Catalina 

<img width="792" alt="polyglot" src="https://user-images.githubusercontent.com/73508422/97247348-15511980-1832-11eb-9a44-f44f99b0e7fa.png">

It just rotates but does not translate

**Comment by gingerbeardman** [comment]
Yes, Google Translate API limit has been exceeded. Wait a while and try again.

This needs a suitable error message.

See #55
