### ISSUE TITLE
dark Mode at source class

### ISSUE THREAD

**Issue by dairan** [uetchy/Polyglot#83]
**Describe the bug**
Colors at class="source" are hard do see at dark mode on MacOS 10.15.7 (19H2) and safari Version 14.0 (15610.1.28.1.9, 15610)

**To Reproduce**

1. Go to https://developer.apple.com/documentation/uikit/uibarbuttonitem/1617153-init
2. Click on Apple Logo () System Preferences -> General  -> alternante between Light and Dark mode and see url at item 1.

**Expected behavior**
The colors at class="source" are hard do see.

**Screenshots**
When Light Mode is on, source class is ok. https://d.pr/i/Dibb0H
But when Dark Mode is on, source class is messy: https://d.pr/i/TWIuHQ

- Version
Polyglot 3.1
MacOS 10.15.7 (19H2) 
Safari 14.0 (15610.1.28.1.9, 15610)

**Comment by gingerbeardman** [comment]
Previously solved in #60, will need working into a solution for Big Sur whilst keeping backwards compatibility.

**Comment by uetchy** [comment]
Thanks for reporting. This is due to a CSS variable declaration in `:root` that accidentally breaks the styles of the visited site. The fix will be in the next version.
