### ISSUE TITLE
Hotkeys don't work

### ISSUE THREAD

**Issue by AlexShvetsovKeepsolid** [uetchy/Polyglot#84]
Hello. I love your extension! But notice one bug: I cannot use hotkeys. I tried to set several different combinations but it doesn't work. 
Safari - 14, app version - 3.1

**Comment by uetchy** [comment]
@AlexShvetsovKeepsolid Try 3.2 released today and see if the problem persists, thanks for reporting!

**Comment by AlexShvetsovKeepsolid** [comment]
Hey. I think this has been fixed in version 3.2. When I installed the new update, the hotkeys still didn't work. But after a few changes the hotkey combination, it starts working. 
<img width="1008" alt="Screenshot 2021-01-06 at 12 49 04" src="https://user-images.githubusercontent.com/72204782/103760349-a6582400-501d-11eb-9fad-3d7335748a26.png">

**Comment by AlexShvetsovKeepsolid** [comment]
Oh, I forgot. Thank you very much
