### ISSUE TITLE
it keep spinning

### ISSUE THREAD

**Issue by hnonstoph** [uetchy/Polyglot#85]
when i run the extension first time, it work perfectly and smooth. But after few minutes, it keeps spinning and so no result. sometime it works sometime not.
<img width="722" alt="Ảnh chụp Màn hình 2020-11-26 lúc 21 18 51" src="https://user-images.githubusercontent.com/48861811/100361682-0a55f880-302d-11eb-8cf3-0f17addb3197.png">

**Comment by gingerbeardman** [comment]
API limit exceeded, wait a while and try again.

See #55 and #82, #77, #73, #41
