### ISSUE TITLE
Polyglot no longer translate for me 

### ISSUE THREAD

**Issue by alexrogalski** [uetchy/Polyglot#87]
<img width="1440" alt="Screenshot 2020-12-30 at 13 20 05" src="https://user-images.githubusercontent.com/55143746/103350974-faa15800-4aa1-11eb-98c0-fa5451b40a94.png">

Its all the time loading. It was my favorite extension :(

**Comment by gingerbeardman** [comment]
Google Translate API limit exceeded.

Solution: slow down your usage, or wait a while and try again.

We need to re-add a message when this happens.

See #55 and #85, #82, #77, #73, #41
